package com.mycompany.perpustakaan;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author akbar
 */
public class Buku extends javax.swing.JFrame {
    private void tampilData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Buku");
    model.addColumn("Judul");
    model.addColumn("Penulis");
    model.addColumn("Penerbit");
    model.addColumn("Tahun");
    model.addColumn("Stok");

    try {
        String sql = "SELECT * FROM buku";
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6)});
        }
        tabelBuku.setModel(model);
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}

private void kosongkanForm() {
    txtId.setText("");
    txtJudul.setText("");
    txtPenulis.setText("");
    txtPenerbit.setText("");
    txtTahun.setText("");
    txtStok.setText("");
    txtId.requestFocus();
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Buku.class.getName());

 
    public Buku() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtJudul = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtPenulis = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBuku = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        clsBtn = new javax.swing.JButton();
        uptBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        smtBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        txtJudul.setBackground(new java.awt.Color(30, 30, 46));
        txtJudul.setForeground(new java.awt.Color(166, 173, 200));
        txtJudul.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 173, 200), 2), "JUDUL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        txtJudul.addActionListener(this::txtJudulActionPerformed);

        txtId.setBackground(new java.awt.Color(30, 30, 46));
        txtId.setForeground(new java.awt.Color(166, 173, 200));
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 173, 200), 2), "ID BUKU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N

        txtPenulis.setBackground(new java.awt.Color(30, 30, 46));
        txtPenulis.setForeground(new java.awt.Color(166, 173, 200));
        txtPenulis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 173, 200), 2), "PENULIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N

        txtStok.setBackground(new java.awt.Color(30, 30, 46));
        txtStok.setForeground(new java.awt.Color(166, 173, 200));
        txtStok.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 173, 200), 2), "STOK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N

        txtPenerbit.setBackground(new java.awt.Color(30, 30, 46));
        txtPenerbit.setForeground(new java.awt.Color(166, 173, 200));
        txtPenerbit.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 173, 200), 2), "PENERBIT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N

        txtTahun.setBackground(new java.awt.Color(30, 30, 46));
        txtTahun.setForeground(new java.awt.Color(166, 173, 200));
        txtTahun.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 173, 200), 2), "TAHUN TERBIIT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N

        tabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul", "Penulis", "Penerbit", "Tahun Terbit", "Stok"
            }
        ));
        tabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBukuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DOUBLE(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBuku);

        jButton2.setBackground(new java.awt.Color(137, 180, 250));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        clsBtn.setBackground(new java.awt.Color(243, 139, 168));
        clsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clsBtn.setText("Close");
        clsBtn.addActionListener(this::clsBtnActionPerformed);

        uptBtn.setBackground(new java.awt.Color(137, 180, 250));
        uptBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uptBtn.setText("Update");
        uptBtn.addActionListener(this::uptBtnActionPerformed);

        delBtn.setBackground(new java.awt.Color(243, 139, 168));
        delBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delBtn.setText("Delete");
        delBtn.addActionListener(this::delBtnActionPerformed);

        smtBtn.setBackground(new java.awt.Color(166, 227, 161));
        smtBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        smtBtn.setText("Submit");
        smtBtn.addActionListener(this::smtBtnActionPerformed);

        jLabel1.setBackground(new java.awt.Color(137, 180, 250));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(137, 180, 250));
        jLabel1.setText("BOOK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(delBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(clsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(smtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtId)
                                    .addComponent(txtJudul)
                                    .addComponent(txtPenulis)
                                    .addComponent(txtTahun)
                                    .addComponent(txtStok)
                                    .addComponent(txtPenerbit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(smtBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uptBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clsBtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smtBtnActionPerformed
    String id = txtId.getText();
    String Judul = txtJudul.getText();
    String Penulis = txtPenulis.getText();
    String Penerbit = txtPenerbit.getText();
    String Tahun = txtTahun.getText();
    String Stok = txtStok.getText();
    
    if (id.isEmpty() || Judul.isEmpty() || Penulis.isEmpty() || Penerbit.isEmpty() || Tahun.isEmpty() || Stok.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "LENGKAPI DATA!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        
    } else {
        try {
        String sql = "INSERT INTO buku (id_buku, judul, penulis, penerbit, tahun_terbit, stok) VALUES (?, ?, ?, ?, ?, ?)";
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, txtId.getText());
        pst.setString(2, txtJudul.getText());
        pst.setString(3, txtPenulis.getText());
        pst.setString(4, txtPenerbit.getText());
        pst.setString(5, txtTahun.getText());
        pst.setString(6, txtStok.getText());
        
        pst.execute();
        javax.swing.JOptionPane.showMessageDialog(null, "Penyimpanan Data Buku Berhasil");
        tampilData(); 
        kosongkanForm();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }      }  // TODO add your handling code here:
    }//GEN-LAST:event_smtBtnActionPerformed

    private void clsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsBtnActionPerformed
         // TODO add your handling code here:
         
    Main_Menu menu = new Main_Menu();
    menu.setVisible(true);
    menu.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_clsBtnActionPerformed

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void uptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uptBtnActionPerformed
    String id = txtId.getText();
    String Judul = txtJudul.getText();
    String Penulis = txtPenulis.getText();
    String Penerbit = txtPenerbit.getText();
    String Tahun = txtTahun.getText();
    String Stok = txtStok.getText();
    
    if (id.isEmpty() || Judul.isEmpty() || Penulis.isEmpty() || Penerbit.isEmpty() || Tahun.isEmpty() || Stok.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "LENGKAPI DATA!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        
    } else {                                
    try {
        String sql = "UPDATE buku SET judul=?, penulis=?, penerbit=?, tahun_terbit=?, stok=? WHERE id_buku=?";
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, txtJudul.getText());
        pst.setString(2, txtPenulis.getText());
        pst.setString(3, txtPenerbit.getText());
        pst.setString(4, txtTahun.getText());
        pst.setString(5, txtStok.getText());
        pst.setString(6, txtId.getText());
        
        pst.execute();
        javax.swing.JOptionPane.showMessageDialog(null, "Data Buku Berhasil Diubah");
        tampilData();
        kosongkanForm();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }   }   // TODO add your handling code here:
    }//GEN-LAST:event_uptBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Hapus buku ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            String sql = "DELETE FROM buku WHERE id_buku=?";
            java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtId.getText());
            
            pst.execute();
            javax.swing.JOptionPane.showMessageDialog(null, "Data Buku Berhasil Dihapus");
            tampilData();
            kosongkanForm();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    kosongkanForm();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBukuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelBukuMouseClicked

    private void DOUBLE(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOUBLE
        if (evt.getClickCount() == 2) {
       
       
        int baris = tabelBuku.getSelectedRow();
        
        String id = tabelBuku.getValueAt(baris, 0).toString();
        String judul = tabelBuku.getValueAt(baris, 1).toString();
        String penulis = tabelBuku.getValueAt(baris, 2).toString();
        String penerbit = tabelBuku.getValueAt(baris, 3).toString();
        String tahun = tabelBuku.getValueAt(baris, 4).toString();
        String stok = tabelBuku.getValueAt(baris, 5).toString();
        
        txtId.setText(id);
        txtJudul.setText(judul);
        txtPenulis.setText(penulis);
        txtPenerbit.setText(penerbit);
        txtTahun.setText(tahun);
        txtStok.setText(stok);
        
        
    } // TODO add your handling code here:
    }//GEN-LAST:event_DOUBLE

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Buku().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clsBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton smtBtn;
    private javax.swing.JTable tabelBuku;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JButton uptBtn;
    // End of variables declaration//GEN-END:variables
}
