/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpustakaan;
import java.io.InputStream;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author akbar
 */
public class Laporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Laporan.class.getName());
private void tampilkanLaporan(String namaFileJasper) {
    try {
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        String path = "/Report/" + namaFileJasper;
        InputStream reportStream = getClass().getResourceAsStream(path);
        
        if (reportStream == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "File " + namaFileJasper + " tidak ditemukan!");
            return;
        }
        
        HashMap parameter = new HashMap();
        JasperPrint print = JasperFillManager.fillReport(reportStream, parameter, conn);
        JasperViewer.viewReport(print, false);
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Menampilkan Laporan: " + e.getMessage());
        e.printStackTrace();
    }
}
    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        viewbtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Stok Buku", "Laporan Member", "Laporan Peminjaman yang Belum Kembali", "Laporan Member Paling Sering Pinjam", "Laporan Buku Paling Sering Dipinjam" }));

        viewbtn.setText("View");
        viewbtn.addActionListener(this::viewbtnActionPerformed);

        closebtn.setText("Close");
        closebtn.addActionListener(this::closebtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewbtn)
                        .addGap(18, 18, 18)
                        .addComponent(closebtn))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewbtn)
                    .addComponent(closebtn))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
                                  
    String pilihanLaporan = jComboBox1.getSelectedItem().toString();
    
    switch (pilihanLaporan) {
        case "Laporan Stok Buku":
            tampilkanLaporan("StokBuku.jasper"); 
            break;
            
        case "Laporan Member":
            tampilkanLaporan("ReportMember.jasper");
            break;
            
        case "Laporan Peminjaman yang Belum Kembali":
            tampilkanLaporan("BukuBelumKembali.jasper");
            break;
            
        case "Laporan Member Paling Sering Pinjam":
            tampilkanLaporan("MemberSeringPinjam.jasper");
            break;
            
        case "Laporan Buku Paling Sering Dipinjam":
            tampilkanLaporan("BukuTerlaris.jasper");
            break;
            
        default:
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih laporan yang valid!");
            break;
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_viewbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
     Main_Menu menu = new Main_Menu();
    menu.setVisible(true);
    menu.setLocationRelativeTo(null);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Laporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
