/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpustakaan;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.security.MessageDigest;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
/**
 *
 * @author akbar
 */

public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        this.setLocationRelativeTo(null);
        initComponents();
         Color bgBase = new Color(30, 30, 46);
         Color bgSurface = new Color(42, 42, 60);
         Color textMain = new Color(205, 214, 244);
         Color textMuted = new Color(166, 173, 200);
         Color accentBlue = new Color(137, 180, 250);
         Color accentGreen = new Color(166, 227, 161);
         Color accentRed = new Color(243, 139, 168);
         this.setLocationRelativeTo(null);
    
 
    username.setBackground(bgBase);
        username.setForeground(textMain);
        password.setBackground(bgBase);
        password.setForeground(textMain);
        box.setBackground(bgSurface);
        judul.setForeground(accentBlue);
        username.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(textMuted), "username", 0, 0, null, textMuted));
        password.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(textMuted), "Password", 0, 0, null, textMuted));
     
    }
  
private String encryptPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(password.getBytes("UTF-8"));
        StringBuilder hexString = new StringBuilder();
        for (byte b : hash) {
            String hex = Integer.toHexString(0xff & b);
            if (hex.length() == 1) hexString.append('0');
            hexString.append(hex);
        }
        return hexString.toString();
    } catch (Exception ex) {
        return null;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        box = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        DaftarBtn = new javax.swing.JButton();
        judul = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username.setMinimumSize(new java.awt.Dimension(64, 55));
        username.setPreferredSize(new java.awt.Dimension(64, 55));

        password.setPreferredSize(new java.awt.Dimension(64, 55));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enter(evt);
            }
        });

        loginbtn.setBackground(new java.awt.Color(137, 180, 250));
        loginbtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(this::loginbtnActionPerformed);

        closebtn.setBackground(new java.awt.Color(243, 139, 168));
        closebtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(this::closebtnActionPerformed);

        DaftarBtn.setBackground(new java.awt.Color(166, 227, 161));
        DaftarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        DaftarBtn.setText("Register");
        DaftarBtn.addActionListener(this::DaftarBtnActionPerformed);

        judul.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        judul.setText("E-Perpus Login");

        javax.swing.GroupLayout boxLayout = new javax.swing.GroupLayout(box);
        box.setLayout(boxLayout);
        boxLayout.setHorizontalGroup(
            boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(99, 99, 99))
            .addGroup(boxLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(boxLayout.createSequentialGroup()
                            .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(DaftarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addComponent(closebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        boxLayout.setVerticalGroup(
            boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn)
                    .addComponent(DaftarBtn))
                .addGap(18, 18, 18)
                .addComponent(closebtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String masuk(){
        
        try {
        String idUser = username.getText();
        String passInput = new String(password.getPassword());
        String encryptedPass = encryptPassword(passInput);

        
        String sql = "SELECT * FROM petugas WHERE id_petugas=? AND password=?";
        if (idUser.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Username g boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        username.requestFocus();
        } else if (passInput.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "password g boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        password.requestFocus();
        } else {
        
        
        
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idUser);
        pst.setString(2, encryptedPass);
        
        java.sql.ResultSet rsPetugas = pst.executeQuery();
        
    if (rsPetugas.next()) {
                String levelAkses = rsPetugas.getString("jabatan");
                
                if (levelAkses.equalsIgnoreCase("inventaris") || 
                    levelAkses.equalsIgnoreCase("resepsionis") || 
                    levelAkses.equalsIgnoreCase("admin")) {
                     javax.swing.JOptionPane.showMessageDialog(null, "Login Berhasil! Anda login sebagai: " + levelAkses);
                     userSession.setRole(levelAkses);
                     new Main_Menu().setVisible(true);
                     this.dispose(); 
        
                }
                
            } else {
               
                String sqlAnggota = "SELECT * FROM anggota WHERE id_member=? AND password=?";
                java.sql.PreparedStatement pstAnggota = conn.prepareStatement(sqlAnggota);
                pstAnggota.setString(1, idUser);
                pstAnggota.setString(2, encryptedPass);
                java.sql.ResultSet rsAnggota = pstAnggota.executeQuery();

                if (rsAnggota.next()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Login Berhasil sebagai Anggota!");
                    userSession.setRole("member");
                    new Main_Menu().setVisible(true); 
                    this.dispose();
                } else {
                    // 
                    javax.swing.JOptionPane.showMessageDialog(null, "Username atau Password Salah!");
                }
            }}
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        
        return null;
    }
    private void DaftarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarBtnActionPerformed
    new register().setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_DaftarBtnActionPerformed

    private void enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter
    
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
    masuk();
  
    }
    }//GEN-LAST:event_enter

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
      masuk();      // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DaftarBtn;
    private javax.swing.JPanel box;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel judul;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
