/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpustakaan;

/**
 *
 * @author akbar
 */
public class Main_Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main_Menu.class.getName());

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Memberbtn = new javax.swing.JButton();
        Rentbtn = new javax.swing.JButton();
        Returnbtn = new javax.swing.JButton();
        Bukubtn = new javax.swing.JButton();
        Logbtn = new javax.swing.JButton();
        Employeebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Memberbtn.setText("Anggota");
        Memberbtn.addActionListener(this::MemberbtnActionPerformed);

        Rentbtn.setText("Peminjaman");
        Rentbtn.addActionListener(this::RentbtnActionPerformed);

        Returnbtn.setText("Pengembalian");
        Returnbtn.addActionListener(this::ReturnbtnActionPerformed);

        Bukubtn.setText("Bukiu");
        Bukubtn.addActionListener(this::BukubtnActionPerformed);

        Logbtn.setText("Log Book");

        Employeebtn.setText("Petugas");
        Employeebtn.addActionListener(this::EmployeebtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Returnbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bukubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Employeebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rentbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Memberbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Logbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rentbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bukubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Returnbtn)
                    .addComponent(Logbtn)
                    .addComponent(Employeebtn)
                    .addComponent(Memberbtn))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MemberbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberbtnActionPerformed
Member formMember = new Member();
    
   
    formMember.setVisible(true);
    
   
    formMember.setLocationRelativeTo(null);
    
    
    this.dispose(); 
    }//GEN-LAST:event_MemberbtnActionPerformed

    private void ReturnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnbtnActionPerformed
        
    }//GEN-LAST:event_ReturnbtnActionPerformed

    private void BukubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BukubtnActionPerformed
        
    Buku formBuku = new Buku();
    formBuku.setVisible(true);
    formBuku.setLocationRelativeTo(null);
    this.dispose(); 

    }//GEN-LAST:event_BukubtnActionPerformed

    private void EmployeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeebtnActionPerformed

    Petugas formPetugas = new Petugas();
    formPetugas.setVisible(true);
    formPetugas.setLocationRelativeTo(null);
    this.dispose();      
    }//GEN-LAST:event_EmployeebtnActionPerformed

    private void RentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentbtnActionPerformed
    Peminjaman formPeminjaman = new Peminjaman();
    formPeminjaman.setVisible(true);
    formPeminjaman.setLocationRelativeTo(null);
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_RentbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main_Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bukubtn;
    private javax.swing.JButton Employeebtn;
    private javax.swing.JButton Logbtn;
    private javax.swing.JButton Memberbtn;
    private javax.swing.JButton Rentbtn;
    private javax.swing.JButton Returnbtn;
    // End of variables declaration//GEN-END:variables
}
