/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpustakaan;

/**
 *
 * @author akbar
 */
public class Peminjaman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Peminjaman.class.getName());
    
    public void kosongkanForm() {
    tIdBuku.setText("");
    tNoPinjam.setText("");
    tIdAnggota.setText("");
    tNama.setText("");
   
}
    
    public void tampilData(String keyword) {
    
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID Buku");
    model.addColumn("Judul");
    model.addColumn("Penulis");
    model.addColumn("Penerbit");
    model.addColumn("Tahun");
    model.addColumn("Stok");

    try {
        String sql;
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        java.sql.PreparedStatement pst;
        if (keyword.isEmpty()) {
            sql = "SELECT * FROM buku";
            pst = conn.prepareStatement(sql);
        } else {
           
            String pilihan = cCari.getSelectedItem().toString();
            String kolomDB = "id_buku"; 
            
            if (pilihan.equals("Judul Buku")) {
                kolomDB = "judul";
            }
            sql = "SELECT * FROM buku WHERE " + kolomDB + " LIKE ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + keyword + "%");
        }

        java.sql.ResultSet rs = pst.executeQuery();

        // 3. Memasukkan data dari database ke baris tabel Java
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_buku"),
                rs.getString("judul"),
                rs.getString("penulis"),
                rs.getString("penerbit"), 
                rs.getString("tahun_terbit"),
                rs.getString("stok")
            });
        }
        
        
        tblBuku.setModel(model);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data tabel: " + e.getMessage());
    }
}
    
    private void generateNoTransaksi() {
    // 1. Ambil waktu saat ini sebagai basis unik (Format: TahunBulanTanggalJamMenitDetik)
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyMMddHHmmss");
    String timestamp = sdf.format(new java.util.Date());
    
    // 2. Buat objek Pseudo-Random
    java.util.Random rnd = new java.util.Random();
    
    // 3. Hasilkan angka acak dari 0 hingga 999 (3 digit)
    int randomInt = rnd.nextInt(1000); 
    
    // 4. Format angka acak agar selalu 3 digit (contoh: 5 menjadi 005)
    String randomStr = String.format("%03d", randomInt);
    
    // 5. Gabungkan menjadi No Transaksi (Contoh output: PMJ-231024153045-087)
    String noTransaksi = "PMJ-" + timestamp + "-" + randomStr;
    
    // 6. Tampilkan ke dalam JTextField No Peminjaman 
    // Ganti 'tNoPeminjaman' dengan nama variabel textfield Anda yang sebenarnya
    tNoPinjam.setText(noTransaksi);
    
    // Opsional: Kunci textfield agar user tidak bisa mengubahnya secara manual
    tNoPinjam.setEditable(false);
    }
    /**
     * Creates new form Peminjaman
     */
    public Peminjaman() {
        initComponents();
        generateNoTransaksi();
        tampilData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        tNoPinjam = new javax.swing.JTextField();
        tIdAnggota = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tIdBuku = new javax.swing.JTextField();
        cCari = new javax.swing.JComboBox<>();
        tJudul = new javax.swing.JTextField();
        tglPinjam = new com.toedter.calendar.JDateChooser();
        tglKembali = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));

        tNoPinjam.setBackground(new java.awt.Color(30, 30, 46));
        tNoPinjam.setForeground(new java.awt.Color(166, 173, 200));
        tNoPinjam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 214, 244), 2), "NO TRANSAKSI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(205, 214, 244)), "NO TRANSAKSI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tNoPinjam.addActionListener(this::tNoPinjamActionPerformed);

        tIdAnggota.setBackground(new java.awt.Color(30, 30, 46));
        tIdAnggota.setForeground(new java.awt.Color(166, 173, 200));
        tIdAnggota.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 214, 244), 2), "USERNAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tIdAnggota.addActionListener(this::tIdAnggotaActionPerformed);
        tIdAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tIdAnggotaKeyPressed(evt);
            }
        });

        tNama.setEditable(false);
        tNama.setBackground(new java.awt.Color(30, 30, 46));
        tNama.setForeground(new java.awt.Color(166, 173, 200));
        tNama.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 214, 244), 2), "NAMA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tNama.addActionListener(this::tNamaActionPerformed);

        tIdBuku.setBackground(new java.awt.Color(30, 30, 46));
        tIdBuku.setForeground(new java.awt.Color(166, 173, 200));
        tIdBuku.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 214, 244), 2), "CARI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tIdBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tIdBukuKeyPressed(evt);
            }
        });

        cCari.setBackground(new java.awt.Color(30, 30, 46));
        cCari.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cCari.setForeground(new java.awt.Color(166, 173, 200));
        cCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Judul Buku", "ID Buku" }));
        cCari.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 214, 244), 2), "FILTER BY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N

        tJudul.setEditable(false);
        tJudul.setBackground(new java.awt.Color(30, 30, 46));
        tJudul.setForeground(new java.awt.Color(166, 173, 200));
        tJudul.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 214, 244), 2), "JUDUL BUKU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tJudul.addActionListener(this::tJudulActionPerformed);

        tglPinjam.setBackground(new java.awt.Color(30, 30, 46));
        tglPinjam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 214, 244), 2), "TANGGAL PINJAM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tglPinjam.setForeground(new java.awt.Color(166, 173, 200));

        tglKembali.setBackground(new java.awt.Color(30, 30, 46));
        tglKembali.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 214, 244), 2), "TANGGAL KEMBALI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tglKembali.setForeground(new java.awt.Color(166, 173, 200));

        jLabel8.setBackground(new java.awt.Color(137, 180, 250));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(137, 180, 250));
        jLabel8.setText("BORROWING");

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul", "Penulis", "Penerbit", "Tahun", "Stok"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBukuMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        jButton1.setBackground(new java.awt.Color(243, 139, 168));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(243, 139, 168));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Batal");

        jButton3.setBackground(new java.awt.Color(166, 227, 161));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Pinjam");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tglPinjam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cCari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tglKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                    .addComponent(tIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(1, 1, 1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel8)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cCari, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNoPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNoPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNoPinjamActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        String sqlInsert = "INSERT INTO peminjaman (no_transaksi, id_member, id_buku, tgl_pinjam, tgl_kembali, status) VALUES (?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pstInsert = conn.prepareStatement(sqlInsert);
        pstInsert.setString(1, tNoPinjam.getText());
        pstInsert.setString(2, tIdAnggota.getText());
        pstInsert.setString(3, tIdBuku.getText());
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        pstInsert.setString(4, sdf.format(tglPinjam.getDate()));
        pstInsert.setString(5, sdf.format(tglKembali.getDate()));
        pstInsert.setString(6, "Pinjam"); // Status default
        
        pstInsert.execute(); 
        javax.swing.JOptionPane.showMessageDialog(null, "Peminjaman Berhasil!");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Kesalahan: " + e.getMessage());
    }
    kosongkanForm();
    generateNoTransaksi();  
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             // TODO add your handling code here:
         
    Main_Menu menu = new Main_Menu();
    menu.setVisible(true);
    menu.setLocationRelativeTo(null);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tIdBukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdBukuKeyPressed
                                    
    
    String keyword = tIdBuku.getText();
    tampilData(keyword);

    }//GEN-LAST:event_tIdBukuKeyPressed

    private void tJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJudulActionPerformed
     String keyword = tJudul.getText();
    tampilData(keyword);
        // TODO add your handling code here:
    }//GEN-LAST:event_tJudulActionPerformed

    private void tblBukuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMousePressed
     if (evt.getClickCount() == 2) {
        int baris = tblBuku.getSelectedRow();
        String id = tblBuku.getValueAt(baris, 0).toString();
        String judul = tblBuku.getValueAt(baris, 1).toString();
        
        tIdBuku.setText(id);
        tJudul.setText(judul);
    }          // TODO add your handling code here:
    }//GEN-LAST:event_tblBukuMousePressed

    private void tIdAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdAnggotaKeyPressed
          // TODO add your handling code here:
    }//GEN-LAST:event_tIdAnggotaKeyPressed

    private void tIdAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdAnggotaActionPerformed
     try {
        String idDicari = tIdAnggota.getText();
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        String sql = "SELECT * FROM anggota WHERE id_member = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idDicari);
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        // 3. Cek apakah data ditemukan
        if (rs.next()) {
            // Jika ketemu, ambil kolom 'nama_anggota' dan tampilkan di textfield Nama
            tNama.setText(rs.getString("nama"));
            
            // (Opsional) Langsung pindahkan kursor ke kotak ID Buku untuk mempercepat ketikan
            tIdBuku.requestFocus(); 
        } else {
            // Jika ID tidak ada di database
            javax.swing.JOptionPane.showMessageDialog(this, "Data Anggota tidak ditemukan!");
            tNama.setText(""); // Kosongkan kembali nama
            tIdAnggota.requestFocus(); // Kembalikan kursor ke ID Anggota
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Kesalahan: " + e.getMessage());
    }         // TODO add your handling code here:
    }//GEN-LAST:event_tIdAnggotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Peminjaman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField tIdAnggota;
    private javax.swing.JTextField tIdBuku;
    private javax.swing.JTextField tJudul;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNoPinjam;
    private javax.swing.JTable tblBuku;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglPinjam;
    // End of variables declaration//GEN-END:variables
}
