/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpustakaan;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author akbar
 */
public class Pengembalian extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pengembalian.class.getName());
    public void setTanggalSekarang() {
    Date hariIni = new Date();
    SimpleDateFormat formatTanggal = new SimpleDateFormat("yyyy-MM-dd"); 
    String tanggalSekarang = formatTanggal.format(hariIni);
    tglKembali.setText(tanggalSekarang);
    tglKembali.setEditable(false); 
}
    private void kosongkanForm() {
    cTransaksi.removeAllItems();
    tIdAnggota.setText("");
    tNama.setText("");
   
}
    
    
    
   
    /**
     * Creates new form Peminjaman
     */
    public Pengembalian() {
        initComponents();
        setTanggalSekarang();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel2 = new javax.swing.JPanel();
        tIdAnggota = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        cTransaksi = new javax.swing.JComboBox<>();
        tglTenggat = new javax.swing.JTextField();
        tglKembali = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 46));

        jPanel2.setBackground(new java.awt.Color(30, 30, 46));
        jPanel2.setForeground(new java.awt.Color(166, 173, 200));

        tIdAnggota.setBackground(new java.awt.Color(30, 30, 46));
        tIdAnggota.setForeground(new java.awt.Color(166, 173, 200));
        tIdAnggota.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USERNAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tIdAnggota.addActionListener(this::tIdAnggotaActionPerformed);
        tIdAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tIdAnggotaKeyPressed(evt);
            }
        });

        tNama.setEditable(false);
        tNama.setBackground(new java.awt.Color(30, 30, 46));
        tNama.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tNama.setForeground(new java.awt.Color(166, 173, 200));
        tNama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NAMA ANGGOTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        tNama.addActionListener(this::tNamaActionPerformed);

        cTransaksi.setBackground(new java.awt.Color(30, 30, 40));
        cTransaksi.setForeground(new java.awt.Color(166, 173, 200));
        cTransaksi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRANSAKSI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N
        cTransaksi.addActionListener(this::cTransaksiActionPerformed);

        tglTenggat.setEditable(false);
        tglTenggat.setBackground(new java.awt.Color(30, 30, 46));
        tglTenggat.setForeground(new java.awt.Color(166, 173, 200));
        tglTenggat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TANGGAL TENGGAT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N

        tglKembali.setEditable(false);
        tglKembali.setBackground(new java.awt.Color(30, 30, 46));
        tglKembali.setForeground(new java.awt.Color(166, 173, 200));
        tglKembali.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TANGGAL REFUND", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(166, 173, 200))); // NOI18N

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Nama", "Buku", "Tanggal Pinjam", "Tanggal Kembali"
            }
        ));
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPinjamMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPinjam);

        jButton4.setBackground(new java.awt.Color(243, 139, 168));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton2.setBackground(new java.awt.Color(243, 139, 168));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Batal");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(166, 227, 161));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setText("Kembalikan");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel4.setBackground(new java.awt.Color(137, 180, 250));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(137, 180, 250));
        jLabel4.setText("REFUND BOOK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglTenggat, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(432, 432, 432)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(tglTenggat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String noTransaksi = cTransaksi.getSelectedItem().toString();
    String tKembali = tglKembali.getText();
    if(noTransaksi.equals("") || noTransaksi.equals("- Pilih -")) {
        JOptionPane.showMessageDialog(this, "Silakan pilih No Transaksi terlebih dahulu!");
        return;
    }

    try {
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        
        
        String sqlkembali = "UPDATE peminjaman SET tgl_dikembalikan = ?, status = 'kembali' WHERE no_transaksi = ?";
        
        PreparedStatement pstkembali = conn.prepareStatement(sqlkembali);
        pstkembali.setString(1, tKembali);
        pstkembali.setString(2, noTransaksi);
        
        // Eksekusi query
        int update = pstkembali.executeUpdate();
        
        if(update > 0) {
            JOptionPane.showMessageDialog(this, "Buku berhasil dikembalikan!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengembalikan buku. Transaksi tidak ditemukan.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tIdAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdAnggotaKeyPressed
              // TODO add your handling code here:
    }//GEN-LAST:event_tIdAnggotaKeyPressed

    private void tIdAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdAnggotaActionPerformed
     
    try {
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        cTransaksi.removeAllItems();
        String idAnggota = tIdAnggota.getText();
        String sqlA = "SELECT * FROM anggota WHERE id_member = ?";
        java.sql.PreparedStatement pstanggota = conn.prepareStatement(sqlA);
        pstanggota.setString(1, idAnggota);
        java.sql.ResultSet rs = pstanggota.executeQuery();
         if (rs.next()) {
            tNama.setText(rs.getString("nama"));
            
          
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Anggota tidak ditemukan!");
            tNama.setText("");
            tIdAnggota.requestFocus();
         }
        pstanggota.setString(1, idAnggota);
        if (idAnggota.trim().isEmpty()) {
            return;
        }
        
        
        String sql = "SELECT no_transaksi, id_buku FROM peminjaman WHERE id_member = ? AND status = 'Pinjam'";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idAnggota);
        
        java.sql.ResultSet rs1 = pst.executeQuery();
        boolean adaData = false;
        while (rs1.next()) {
            adaData = true;
            cTransaksi.addItem(rs1.getString("no_transaksi"));
        }
        if (!adaData) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada transaksi peminjaman aktif untuk Anggota ini!");
            tIdAnggota.requestFocus();
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Kesalahan: " + e.getMessage());
    }       // TODO add your handling code here:
    }//GEN-LAST:event_tIdAnggotaActionPerformed

    private void tblPinjamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMousePressed
          // TODO add your handling code here:
    }//GEN-LAST:event_tblPinjamMousePressed

    private void cTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTransaksiActionPerformed
                                                 
    if (cTransaksi.getSelectedItem() == null) {
        return; 
    }
    String noTransaksi = cTransaksi.getSelectedItem().toString();

    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("No Transaksi");
    model.addColumn("Nama");
    model.addColumn("Buku"); 
    model.addColumn("Tanggal Pinjam");
    model.addColumn("Tanggal Kembali");

    try {
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();

        String sql = "SELECT p.no_transaksi, a.nama, b.judul, p.tgl_pinjam, p.tgl_kembali " +
                     "FROM peminjaman p " +
                     "JOIN anggota a ON p.id_member = a.id_member " + 
                     "JOIN buku b ON p.id_buku = b.id_buku " +
                     "WHERE p.no_transaksi = ?";
                     
        java.sql.PreparedStatement pstkembali = conn.prepareStatement(sql);
        pstkembali.setString(1, noTransaksi);
        
        java.sql.ResultSet rs = pstkembali.executeQuery();
        if (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("no_transaksi"),
                rs.getString("nama"),
                rs.getString("judul"),
                rs.getString("tgl_pinjam"),
                rs.getString("tgl_kembali")
            });
            
            tglTenggat.setText(rs.getString("tgl_kembali")); 
        }

        tblPinjam.setModel(model);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error memuat detail transaksi: " + e.getMessage());
    }     // TODO add your handling code here:
    }//GEN-LAST:event_cTransaksiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             // TODO add your handling code here:
         
    Main_Menu menu = new Main_Menu();
    menu.setVisible(true);
    menu.setLocationRelativeTo(null);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pengembalian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cTransaksi;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField tIdAnggota;
    private javax.swing.JTextField tNama;
    private javax.swing.JTable tblPinjam;
    private javax.swing.JTextField tglKembali;
    private javax.swing.JTextField tglTenggat;
    // End of variables declaration//GEN-END:variables
}
