/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpustakaan;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author akbar
 */
public class Pengembalian extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pengembalian.class.getName());
    public void setTanggalSekarang() {
    Date hariIni = new Date();
    SimpleDateFormat formatTanggal = new SimpleDateFormat("yyyy-MM-dd"); 
    String tanggalSekarang = formatTanggal.format(hariIni);
    tglKembali.setText(tanggalSekarang);
    tglKembali.setEditable(false); 
}
    private void kosongkanForm() {
    cTransaksi.removeAllItems();
    tIdAnggota.setText("");
    tNama.setText("");
   
}
    
    
    
   
    /**
     * Creates new form Peminjaman
     */
    public Pengembalian() {
        initComponents();
        setTanggalSekarang();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        tIdAnggota = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();
        tglTenggat = new javax.swing.JTextField();
        tglKembali = new javax.swing.JTextField();
        cTransaksi = new javax.swing.JComboBox<>();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tIdAnggota.addActionListener(this::tIdAnggotaActionPerformed);
        tIdAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tIdAnggotaKeyPressed(evt);
            }
        });

        tNama.setEditable(false);
        tNama.addActionListener(this::tNamaActionPerformed);

        jLabel1.setText("No Transaksi");

        jLabel2.setText("ID Anggota");

        jLabel3.setText("Nama Anggota");

        jLabel6.setText("Tanggal Tenggat");

        jLabel7.setText("Tanggal Kembali");

        jButton2.setText("Batal");

        jButton3.setText("Kembalikan");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Nama", "Buku", "Tanggal Pinjam", "Tanggal Kembali"
            }
        ));
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPinjamMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPinjam);

        tglTenggat.setEditable(false);

        tglKembali.setEditable(false);

        cTransaksi.addActionListener(this::cTransaksiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tglKembali, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglTenggat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tglTenggat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String noTransaksi = cTransaksi.getSelectedItem().toString();
    String tKembali = tglKembali.getText();
    if(noTransaksi.equals("") || noTransaksi.equals("- Pilih -")) {
        JOptionPane.showMessageDialog(this, "Silakan pilih No Transaksi terlebih dahulu!");
        return;
    }

    try {
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        
        
        String sqlkembali = "UPDATE peminjaman SET tgl_dikembalikan = ?, status = 'kembali' WHERE no_transaksi = ?";
        
        PreparedStatement pstkembali = conn.prepareStatement(sqlkembali);
        pstkembali.setString(1, tKembali);
        pstkembali.setString(2, noTransaksi);
        
        // Eksekusi query
        int update = pstkembali.executeUpdate();
        
        if(update > 0) {
            JOptionPane.showMessageDialog(this, "Buku berhasil dikembalikan!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengembalikan buku. Transaksi tidak ditemukan.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tIdAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdAnggotaKeyPressed
              // TODO add your handling code here:
    }//GEN-LAST:event_tIdAnggotaKeyPressed

    private void tIdAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdAnggotaActionPerformed
     
    try {
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();
        cTransaksi.removeAllItems();
        String idAnggota = tIdAnggota.getText();
        String sqlA = "SELECT * FROM anggota WHERE id_member = ?";
        java.sql.PreparedStatement pstanggota = conn.prepareStatement(sqlA);
        pstanggota.setString(1, idAnggota);
        java.sql.ResultSet rs = pstanggota.executeQuery();
         if (rs.next()) {
            tNama.setText(rs.getString("nama"));
            
          
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Anggota tidak ditemukan!");
            tNama.setText("");
            tIdAnggota.requestFocus();
         }
        pstanggota.setString(1, idAnggota);
        if (idAnggota.trim().isEmpty()) {
            return;
        }
        
        
        String sql = "SELECT no_transaksi, id_buku FROM peminjaman WHERE id_member = ? AND status = 'Pinjam'";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idAnggota);
        
        java.sql.ResultSet rs1 = pst.executeQuery();
        boolean adaData = false;
        
        // 3. Masukkan setiap nomor peminjaman yang ditemukan ke dalam ComboBox
        while (rs1.next()) {
            adaData = true;
            cTransaksi.addItem(rs1.getString("no_transaksi"));
        }
        if (!adaData) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada transaksi peminjaman aktif untuk Anggota ini!");
            tIdAnggota.requestFocus();
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Kesalahan: " + e.getMessage());
    }       // TODO add your handling code here:
    }//GEN-LAST:event_tIdAnggotaActionPerformed

    private void tblPinjamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMousePressed
          // TODO add your handling code here:
    }//GEN-LAST:event_tblPinjamMousePressed

    private void cTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTransaksiActionPerformed
                                                 
    if (cTransaksi.getSelectedItem() == null) {
        return; 
    }
    String noTransaksi = cTransaksi.getSelectedItem().toString();

    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("No Transaksi");
    model.addColumn("Nama");
    model.addColumn("Buku"); // Menampilkan Judul Buku
    model.addColumn("Tanggal Pinjam");
    model.addColumn("Tanggal Kembali");

    try {
        java.sql.Connection conn = (java.sql.Connection) Koneksi.configDB();

        String sql = "SELECT p.no_transaksi, a.nama, b.judul, p.tgl_pinjam, p.tgl_kembali " +
                     "FROM peminjaman p " +
                     "JOIN anggota a ON p.id_member = a.id_member " + 
                     "JOIN buku b ON p.id_buku = b.id_buku " +
                     "WHERE p.no_transaksi = ?";
                     
        java.sql.PreparedStatement pstkembali = conn.prepareStatement(sql);
        pstkembali.setString(1, noTransaksi);
        
        java.sql.ResultSet rs = pstkembali.executeQuery();

        // 5. Masukkan data ke dalam baris tabel
        if (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("no_transaksi"),
                rs.getString("nama"),
                rs.getString("judul"),
                rs.getString("tgl_pinjam"),
                rs.getString("tgl_kembali")
            });
            
            // 6. Otomatis mengisi textfield Tanggal Tenggat
            // Pastikan variabel textfield tanggal tenggat Anda bernama tTenggat
            tglTenggat.setText(rs.getString("tgl_kembali")); 
        }

        // 7. Terapkan model ke JTable di form Anda
        // Ganti 'tblPengembalian' dengan nama variabel JTable Anda yang sebenarnya
        tblPinjam.setModel(model);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error memuat detail transaksi: " + e.getMessage());
    }     // TODO add your handling code here:
    }//GEN-LAST:event_cTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pengembalian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cTransaksi;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField tIdAnggota;
    private javax.swing.JTextField tNama;
    private javax.swing.JTable tblPinjam;
    private javax.swing.JTextField tglKembali;
    private javax.swing.JTextField tglTenggat;
    // End of variables declaration//GEN-END:variables
}
